### ISSUE TITLE
 'StaticJsonBuffer' was not declared in this scope

### ISSUE THREAD

**Issue by bphermansson** [bphermansson/EspSparsnasGateway#19]
The code fails to compile if you updated ArduinoJson recently. This is because the Library Manager installs version 6.0 beta of ArduinoJson. The solution is to downgrade to the stable version 5.13.2. 
See https://github.com/bblanchon/ArduinoJson/issues/756 for more info.

**Comment by bblanchon** [comment]
You can verify that the right version of ArduinoJson is installed by checking the [ARDUINOJSON_VERSION](https://arduinojson.org/v5/api/utils/version/?utm_source=github&utm_medium=issues) macros.

**Comment by Netoperz** [comment]
Yap, i can confirm that bug.
all beta 's have problem, and only 5 works fine, , question is why arduino is pushing the updates to beta versions? should't that be only production version availble and dev only for those who want that ? :D

**Comment by dogmatic69** [comment]
You choose the version you want when you install it, so if you don't want beta don't choose it.

**Comment by dogmatic69** [comment]
This ticket should be closed (it is not really a bug, only information). It should be placed in the README
