### ISSUE TITLE
Text corrections?

### ISSUE THREAD

**Issue by Naesstrom** [bphermansson/EspSparsnasGateway#21]
Just wanted to check what instructions to follow, in the build instructions you suggest using a "330-470uF" capacitor but in the links and the schematic it's a 1000uF?

**Comment by bphermansson** [comment]
I think 330uF is enough but larger wont hurt. Use what you have and have room for.

**Comment by Naesstrom** [comment]
Sweet, still waiting for my PCB's but think I have all the parts already! 
![screen shot 2018-09-20 at 08 18 17](https://user-images.githubusercontent.com/6575206/45799453-e01a8a80-bcad-11e8-8b2b-9bd3107092b6.png)
