### ISSUE TITLE
Use the RFM69 libs directly

### ISSUE THREAD

**Issue by dogmatic69** [bphermansson/EspSparsnasGateway#37]
Currently there is a "copy" of that lib in here meaning we need to maintain it. We should replace all the RMF69 code with what is provided with the [lib](https://github.com/LowPowerLab/RFM69).

That will also make this work on more boards out the box.

**Comment by bphermansson** [comment]
I tried to get this working but failed. Seems you have to adjust settings in the lib itself for it to work in this application, and then the meaning with using the lib is almost gone. 
There shall be a possibility to change the library files at compile time with PlatformIO, but I don't think i'ts worth it.
