### ISSUE TITLE
Issue that values written to MQTT broker does not show the right values

### ISSUE THREAD

**Issue by swapper82** [bphermansson/EspSparsnasGateway#4]
When publishing to a mosquitto broker (at least) 
i got the values {"seq":989,"power":true,"total":true,"battery":100}
Interprited as bolean values or somting?

i "fixed" the issue by changing to float from string (starting line 458 in the main .ino file)

      else {
        root["seq"] = seq;
        root["power"] = float(watt);
        root["total"] = float(pulse / PULSES_PER_KWH);
        root["battery"] = battery;
        root["rssi"] = float(srssi);
      }

Thanx for a GREAT project :)

**Comment by bphermansson** [comment]
Your'e welcome!
Ok, I guess the values are interpreted different with different softwares. But the power and total values are indeed numbers, so I see no problem sending them as floats. I've changed this in the main branch, thanks for the report.
