### ISSUE TITLE
Enable second transmitter id

### ISSUE THREAD

**Issue by SweNilsson** [bphermansson/EspSparsnasGateway#50]
By monitoring more than one energy meter at home it would be possible to keep consumption from the Car and the Heating system on separate "tabs". I imagine that the code change would be rather small, but I can't achieve this myself with my lacking programming skills. My current need is to receive data from two transmitters.

My idea to solve the need:
Setup transmitter_id2 in settings.h
either add watt2, total2 and battery2 to the MQTT message or create a separate message in case two transmitter ids have been set.

**Comment by Sperra** [comment]
You can try this one: https://github.com/Sperra/EspSparsnasGateway

**Comment by SweNilsson** [comment]
Thanks @Sperra ! What is the json value ids? I've tried to check the code but I'm not qualified to read it. Today I have a sensor reading this "value_json.watt" but now I need two different I guess?

**Comment by Sperra** [comment]
During startup and initializing it uses the following for information and debug.
EspSparsnasGateway/values
EspSparsnasGateway/debug

Meassurment are sent with the following
EspSparsnasGateway/Sensor1/values
EspSparsnasGateway/Sensor1/debug
EspSparsnasGateway/Sensor2/values
EspSparsnasGateway/Sensor2/debug

Values are the same as before: seq, timestamp, watt, total, battery and rssi

I have the following setup for wat in my OpenHAB
Number sensors_sparsnas_watt "watt [%.1f W]" (gpower) {mqtt="<[mosquitto:EspSparsnasGateway/Sensor1/values:state:JSONPATH($.watt)]"}

**Comment by SweNilsson** [comment]
Great! Exactly what I was looking for

**Comment by bphermansson** [comment]
Great work! Just wished it'd been a PR here instead of a fork.

**Comment by Sperra** [comment]
Sprry my faiult! Totaly new to GitHub. I will try to do a PR  during het weekend.

**Comment by dogmatic69** [comment]
It's easy to make a [PR from a fork](https://github.com/bphermansson/EspSparsnasGateway/compare/master...Sperra:master) 

It needs cleaning up before being merged though.
