### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by pettib** [bphermansson/EspSparsnasGateway#6]
Hi
I´m trying to compile to project and got error that functions can not be found.
I´m guessing there are something missing, but cant find it.
The board is Wemos D1 running at 115200.

[error.txt](https://github.com/bphermansson/EspSparsnasGateway/files/1714513/error.txt)

regards Peter

**Comment by bphermansson** [comment]
Is this the problem with paths that were solved in the Facebook-thread?
