### ISSUE TITLE
Use a Mqtt ping to avoid disconnection

### ISSUE THREAD

**Issue by bphermansson** [bphermansson/EspSparsnasGateway#7]
Make the device send a Mqtt message, a "ping", at regular intervalls to avoid disconnection from the broker.

**Comment by dogmatic69** [comment]
The pubsub lib already implements a keepalive (`MQTT_KEEPALIVE`) that is pre-set to 15 seconds. There is no need to add another.

**Comment by dogmatic69** [comment]
I have configured the ping timeout to a larger value and in 20 minutes have not had a single re-connection.
