### ISSUE TITLE
Calculates wrongly when low/none power usage

### ISSUE THREAD

**Issue by tubalainen** [bphermansson/EspSparsnasGateway#9]
The code calculates watts extremely oddly when there isnt a significant load, for example, a load greater than 1000 W.

It reports like 39302 watts when there should be 7 W only.

**Comment by bphermansson** [comment]
This we have to look into. Too bad I only have one sender and it's mounted at the power meter. Will see if it's possible to fake values in the code to trigger this bug.

**Comment by Sperra** [comment]
Even I have problems with incorrect and extreme values ​​of effects up to 1.6MW on a 20A main circuit.

The power is calculated according to "watt = (float) ((3600000 / PULSES_PER_KWH) * 1024) / (power);"
Here in the code "power" takes 2bytes.

A high value of "power" will give a low power in W, a value of 65535 produces a minimum power of about 56W. Lower effects seem to get the value of "power" to switch over and start from 0. This seems to match my OpenHab which shows 1.572MW power output. 1.572MW should then correspond to just under 56W the wattage is more reasonable when the values ​​around such a peak are around 80W.

**Comment by bphermansson** [comment]
I'm thinking of letting the code just send raw values, calculations then has to be done by the receiver. 

Wonder if this error also shows with Strigeus code, https://github.com/strigeus/sparsnas_decoder?

**Comment by tubalainen** [comment]
Looks like the bug exists in the original code as well. Or, there is something fishy with my sparsnäs used for that measurement (got two here at home). The display shows correct values, but both SDR and ESP solution shows the same..

One "ugly fix" is to consider everything under 100 W as 0 in the code... That would help me.

**Comment by bphermansson** [comment]
Hmm wait... power is stored in the code as an int, and can therefor be a signed number from -32768 to 32767. The value in the data from the sender is 16 bits with a max of 65535. Not good.
Changing the power type to uint should fix this issue.

**Comment by bphermansson** [comment]
That fix is in the code now, hope it works.

**Comment by fredrike** [comment]
According to @tubalainen did the `u_int` not help. I've been talking to @bhaap today and apparently was this issue introduced on @tubalainen's code when I changed `PULSES_PER_KWH` from a defined constant to an `int`.

```c
        float watt =  (float)((3600000 / PULSES_PER_KWH) * 1024) / (power);
```

Do we have any samples of output with what the `power` is after the change to `u_int`?  Would it be better to have `power` as `uint16_t`?
